wereldfietser_wereldfietser_controller:
    path: /demo/{name}
    defaults: { _controller: wereldfietser.wereldfietser.controller.main:handle }

wereldfietser_wereldfietser_merge_controller:
    path: /account-merge
    defaults: { _controller: wereldfietser.wereldfietser.controller.merge:handle }
